version: '3'

services: 
  app:
    build:
      context: .
      args: 
        - APP_PORT=3333
    container_name: app
    restart: always
    tty: true
    volumes: 
      - .:/var/www
    depends_on:
      - db
      - redis
    entrypoint: dockerize -template ./.docker/app/.env:.env -template ./.docker/app/.env.testing:.env.testing -template ./.docker/app/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf -wait tcp://db:3306 -timeout 40s ./.docker/wait_for_it.sh
    environment: 
      - _DB_HOST=db
      - _DB_DATABASE=code_micro_videos
      - _DB_USERNAME=root
      - _DB_PASSWORD=root
      - FPM_PORT=3333
      - _TEST_DB_DATABASE=code_micro_videos_test
    networks: 
      - app-network
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    volumes: 
      - .:/var/www
    networks: 
      - app-network
    depends_on: 
      - app
    environment: 
      - APP_HOST=app
      - APP_PORT=3333
    entrypoint: dockerize -template ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf -wait tcp://app:3333 -timeout 40s ./.docker/nginx/start.sh
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports: 
      - "1234:3306"
    volumes: 
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - app-network
  redis:
    image: redis:alpine
    container_name: redis
    expose: 
      - 6379
    volumes: 
      - ./.docker/rddata:/var/lib/redis
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge

  